# ---------------------------------------------------------------------------------------------------------------------
# GP3 STORAGE CLASS
# Default StorageClass for EBS volumes. Used by Dagster PostgreSQL PVC.
# Requires aws-ebs-csi-driver addon installed on EKS cluster.
# ---------------------------------------------------------------------------------------------------------------------
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  type: gp3
  encrypted: "true"
